# Chapter 5 - Model Evaluation and Improvement

This notebook contains code reproductions, theoretical explanations, and discussions based on Chapter 5 of *Introduction to Machine Learning with Python: A Guide for Data Scientists* by Andreas C. Müller and Sarah Guido.

## Chapter Summary

Building a machine learning model is only one part of the process. Evaluating model performance and improving model quality are equally important.

This chapter introduces evaluation strategies such as train-test split, cross-validation, grid search, and performance metrics. It also discusses methods for selecting model parameters and comparing machine learning models.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mglearn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

%matplotlib inline

# Cross Validation

Cross-validation is a technique used to evaluate machine learning models more reliably.

Instead of using a single train-test split, the dataset is divided into multiple folds. The model is trained and evaluated several times using different subsets of the data.

In [3]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

iris = load_iris()

logreg = LogisticRegression(
    max_iter=1000
)

scores = cross_val_score(
    logreg,
    iris.data,
    iris.target,
    cv=5
)

print("Cross-validation scores:")
print(scores)

Cross-validation scores:
[0.96666667 1.         0.93333333 0.96666667 1.        ]


In [4]:
print("Average cross-validation score: {:.3f}".format(
    scores.mean()
))

Average cross-validation score: 0.973


### Discussion

Cross-validation provides a more robust estimate of model performance because the model is evaluated on multiple train-test splits.

This reduces the risk of obtaining misleading results from a single split.

# K-Fold Cross Validation

K-Fold Cross Validation divides the dataset into K equally sized folds.

Each fold is used once as a test set while the remaining folds are used for training.

In [5]:
from sklearn.model_selection import KFold

kfold = KFold(
    n_splits=5
)

print(kfold)

KFold(n_splits=5, random_state=None, shuffle=False)


In [6]:
scores = cross_val_score(
    logreg,
    iris.data,
    iris.target,
    cv=kfold
)

print(scores)

[1.         1.         0.86666667 0.93333333 0.83333333]


### Discussion

K-Fold validation ensures that all observations participate in both training and testing, leading to more reliable performance estimates.

# Leave-One-Out Cross Validation

Leave-One-Out Cross Validation (LOOCV) uses a single observation as the test set and the remaining observations as the training set.

This process is repeated for every sample in the dataset.

In [7]:
from sklearn.model_selection import LeaveOneOut

loo = LeaveOneOut()

scores = cross_val_score(
    logreg,
    iris.data,
    iris.target,
    cv=loo
)

print("Number of iterations:",
      len(scores))

Number of iterations: 150


### Discussion

LOOCV uses almost all available data for training but can be computationally expensive for large datasets.

# Grid Search

Machine learning models often contain parameters that must be specified before training.

Grid Search is a systematic method for testing multiple parameter combinations and selecting the best configuration.

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

param_grid = {
    "C": [0.1, 1, 10, 100],
    "gamma": [0.001, 0.01, 0.1, 1]
}

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    iris.data,
    iris.target,
    random_state=0
)

grid_search = GridSearchCV(
    SVC(),
    param_grid,
    cv=5
)

grid_search.fit(
    X_train,
    y_train
)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [0.001, 0.01, 0.1, 1]})

In [10]:
print("Best parameters:")
print(grid_search.best_params_)

Best parameters:
{'C': 10, 'gamma': 0.1}


In [11]:
print("Best cross-validation score: {:.3f}".format(
    grid_search.best_score_
))

Best cross-validation score: 0.973


### Discussion

Grid Search automates hyperparameter tuning by evaluating multiple parameter combinations.

This process helps identify settings that produce the best performance.

# Hyperparameter Tuning

Hyperparameters control the behavior of machine learning algorithms and must be selected before training.

Examples include:

- Number of neighbors in KNN
- Tree depth in Decision Trees
- Learning rate in Gradient Boosting
- C and gamma in SVM

In [12]:
print("Best test score: {:.3f}".format(
    grid_search.score(
        X_test,
        y_test
    )
))

Best test score: 0.974


### Discussion

Proper hyperparameter tuning can significantly improve model performance and reduce overfitting.

# Confusion Matrix

A confusion matrix summarizes classification results by comparing actual labels with predicted labels.

It provides more detailed information than accuracy alone.

In [13]:
from sklearn.metrics import confusion_matrix

svc = SVC(
    gamma=0.01,
    C=10
)

svc.fit(
    X_train,
    y_train
)

predictions = svc.predict(
    X_test
)

confusion_matrix(
    y_test,
    predictions
)

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

In [14]:
cm = confusion_matrix(
    y_test,
    predictions
)

print(cm)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


### Discussion

The confusion matrix reveals which classes are correctly classified and which classes are confused with one another.

This information is useful for diagnosing model weaknesses.

# Precision, Recall, and F1 Score

Accuracy alone may not provide a complete picture of model performance.

Precision, Recall, and F1 Score are commonly used to evaluate classification models, especially for imbalanced datasets.

In [15]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        predictions
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



### Discussion

Precision measures how many predicted positive cases are actually positive.

Recall measures how many actual positive cases are successfully detected.

The F1 Score combines precision and recall into a single metric.

# Model Comparison

Model evaluation should consider multiple metrics rather than relying on a single score.

Cross-validation, confusion matrices, and classification metrics provide complementary perspectives on model performance.

# Key Takeaways

This chapter introduced several techniques for evaluating and improving machine learning models:

- Cross Validation
- K-Fold Validation
- Leave-One-Out Validation
- Grid Search
- Hyperparameter Tuning
- Confusion Matrix
- Precision, Recall, and F1 Score

These methods help ensure that machine learning models generalize well to unseen data.