# Chapter 7 - Working with Text Data

This notebook contains code reproductions, theoretical explanations, and discussions based on Chapter 7 of *Introduction to Machine Learning with Python: A Guide for Data Scientists* by Andreas C. Müller and Sarah Guido.

## Chapter Summary

Text data is one of the most common forms of data encountered in machine learning applications.

Unlike numerical data, text must first be transformed into a numerical representation before machine learning algorithms can process it.

This chapter introduces Bag-of-Words, TF-IDF, and text classification techniques using Scikit-Learn.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

# Bag of Words

Machine learning models cannot directly process raw text.

The Bag-of-Words representation converts text into numerical features by counting how often words appear in a document.

In [3]:
bards_words = [
    "The fool doth think he is wise",
    "but the wise man knows himself to be a fool"
]

bards_words

['The fool doth think he is wise',
 'but the wise man knows himself to be a fool']

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()

vect.fit(bards_words)

CountVectorizer()

In [5]:
print("Vocabulary size:",
      len(vect.vocabulary_))

print(vect.vocabulary_)

Vocabulary size: 13
{'the': 9, 'fool': 3, 'doth': 2, 'think': 10, 'he': 4, 'is': 6, 'wise': 12, 'but': 1, 'man': 8, 'knows': 7, 'himself': 5, 'to': 11, 'be': 0}


In [6]:
bag_of_words = vect.transform(
    bards_words
)

print("Bag of words matrix:")
print(bag_of_words.toarray())

Bag of words matrix:
[[0 0 1 1 1 0 1 0 0 1 1 0 1]
 [1 1 0 1 0 1 0 1 1 1 0 1 1]]


### Discussion

CountVectorizer converts text into a numerical matrix where each column represents a unique word and each row represents a document.

The resulting representation allows machine learning algorithms to process textual information.

# Working with Larger Text Collections

Real-world text classification tasks often involve thousands of documents.

Bag-of-Words remains one of the simplest and most effective methods for representing textual information.

In [7]:
text_train = [
    "I love machine learning",
    "Machine learning is amazing",
    "I enjoy data science",
    "Data science is interesting"
]

vect = CountVectorizer()

X_train = vect.fit_transform(
    text_train
)

print(X_train.toarray())

[[0 0 0 0 0 1 1 1 0]
 [1 0 0 0 1 1 0 1 0]
 [0 1 1 0 0 0 0 0 1]
 [0 1 0 1 1 0 0 0 1]]


### Discussion

Each document is transformed into a vector containing word frequencies.

Documents containing similar words often produce similar feature vectors.

# TF-IDF

Term Frequency-Inverse Document Frequency (TF-IDF) improves the Bag-of-Words representation by reducing the influence of extremely common words.

Words that appear frequently in a specific document but not across all documents receive higher importance scores.

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_tfidf = tfidf.fit_transform(
    text_train
)

print(X_tfidf.shape)

(4, 9)


In [9]:
print(tfidf.get_feature_names_out())

['amazing' 'data' 'enjoy' 'interesting' 'is' 'learning' 'love' 'machine'
 'science']


### Discussion

TF-IDF helps highlight words that are more informative for distinguishing documents.

This often improves classification performance compared to simple word counts.

# Text Classification

Text classification is a supervised learning task where documents are assigned to predefined categories.

Examples include spam detection, sentiment analysis, and topic classification.

In [10]:
documents = [
    "I love this movie",
    "This movie is fantastic",
    "I hate this movie",
    "This movie is terrible"
]

labels = [
    1,
    1,
    0,
    0
]

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    documents,
    labels,
    random_state=42
)

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

text_clf = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("clf", LogisticRegression())
])

In [13]:
text_clf.fit(
    X_train,
    y_train
)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LogisticRegression())])

In [14]:
print("Test accuracy: {:.3f}".format(
    text_clf.score(
        X_test,
        y_test
    )
))

Test accuracy: 0.000


### Discussion

The pipeline automatically converts text into TF-IDF features and then trains a Logistic Regression classifier.

This workflow is commonly used in text classification problems.

# Key Takeaways

This chapter introduced:

- Bag of Words
- CountVectorizer
- TF-IDF
- Text Classification
- Text Processing Pipelines

These techniques form the foundation of many natural language processing applications.

# Conclusion

Text data requires special preprocessing before machine learning models can be applied.

This chapter demonstrated how text can be transformed into numerical features using Bag-of-Words and TF-IDF representations. It also introduced basic text classification using machine learning pipelines.

These concepts provide a foundation for more advanced natural language processing techniques.