# Chapter Summary

Data preprocessing is one of the most important stages in the machine learning workflow. Even the most advanced machine learning algorithms cannot perform well if the input data contains errors, missing values, inconsistent formatting, or irrelevant features.

This chapter explores various preprocessing techniques including data cleaning, handling missing values, feature scaling, categorical encoding, pipelines, and feature engineering. These techniques help improve model performance and ensure that machine learning models receive high-quality input data.

# Learning Objectives

After completing this chapter, students should be able to:

- Understand the importance of data preprocessing.
- Identify common data quality issues.
- Handle missing values effectively.
- Apply feature scaling techniques.
- Encode categorical variables.
- Build preprocessing pipelines.
- Perform basic feature engineering.

## The Impact of Raw Data on Model Performance

Machine learning models rely heavily on the quality of the input data.

Poor-quality data may cause:

- Reduced accuracy
- Overfitting
- Underfitting
- Biased predictions
- Poor generalization

Therefore, preprocessing is essential before model training.

In [1]:
import pandas as pd
import numpy as np

data = {
    "Age": [25, 30, np.nan, 40, 35],
    "Salary": [5000, 7000, 6000, np.nan, 8000]
}

df = pd.DataFrame(data)

df

,Age,Salary
0,25.0,5000.0
1,30.0,7000.0
2,NaN,6000.0
3,40.0,NaN
4,35.0,8000.0


## Common Data Issues

Some common problems found in datasets include:

- Missing values
- Duplicate records
- Outliers
- Incorrect data types
- Inconsistent formatting
- Imbalanced classes

These issues can negatively affect model performance if not addressed properly.

In [2]:
print(df.isnull().sum())

Age       1
Salary    1
dtype: int64


## Cleaning and Preparing Data

Data cleaning aims to improve data quality before training.

Common tasks include:

- Removing duplicates
- Fixing incorrect values
- Standardizing formats
- Handling missing values

In [3]:
duplicate_df = pd.DataFrame({
    "A": [1, 1, 2, 2, 3],
    "B": [5, 5, 6, 6, 7]
})

print("Before:")
print(duplicate_df)

duplicate_df = duplicate_df.drop_duplicates()

print("\nAfter:")
print(duplicate_df)

Before:
   A  B
0  1  5
1  1  5
2  2  6
3  2  6
4  3  7

After:
   A  B
0  1  5
2  2  6
4  3  7


## Handling Missing Data

Missing values are among the most common problems in machine learning datasets.

Several strategies can be used:

- Remove rows
- Remove columns
- Mean imputation
- Median imputation
- Most frequent value imputation

In [4]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mean")

imputed_data = imputer.fit_transform(df)

print(imputed_data)

[[  25.  5000. ]
 [  30.  7000. ]
 [  32.5 6000. ]
 [  40.  6500. ]
 [  35.  8000. ]]


The SimpleImputer replaces missing numerical values with the mean value of the corresponding feature.

## Scaling Techniques

Machine learning algorithms often perform better when features are on similar scales.

Common scaling methods:

- StandardScaler
- MinMaxScaler
- RobustScaler

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_data = scaler.fit_transform(imputed_data)

print(scaled_data[:5])

[[-1.5 -1.5]
 [-0.5  0.5]
 [ 0.  -0.5]
 [ 1.5  0. ]
 [ 0.5  1.5]]


In [6]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

normalized_data = minmax.fit_transform(imputed_data)

print(normalized_data[:5])

[[0.         0.        ]
 [0.33333333 0.66666667]
 [0.5        0.33333333]
 [1.         0.5       ]
 [0.66666667 1.        ]]


## Encoding Categorical Variables

Machine learning algorithms generally require numerical input. Therefore, categorical variables must be converted into numerical representations before model training.

Common encoding methods include:

- Label Encoding
- One-Hot Encoding
- Ordinal Encoding

The choice of encoding method depends on the nature of the categorical variable and the machine learning algorithm being used.

In [7]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

colors = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red", "Blue"]
})

encoder = LabelEncoder()

colors["Encoded"] = encoder.fit_transform(colors["Color"])

print(colors)

   Color  Encoded
0    Red        2
1   Blue        0
2  Green        1
3    Red        2
4   Blue        0


In [8]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(colors[["Color"]])

print(encoded)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


Label Encoding assigns a unique integer to each category. One-Hot Encoding creates separate binary columns for each category and is generally preferred when categories do not have an inherent order.

## Introduction to Pipelines in scikit-learn

As machine learning projects grow larger, preprocessing and modeling steps can become difficult to manage.

Pipelines provide a structured approach to combine multiple operations into a single workflow.

Benefits of pipelines:

- Cleaner code
- Improved reproducibility
- Prevention of data leakage
- Easier hyperparameter tuning

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=1000))
])

pipeline.fit(X, y)

print("Pipeline Accuracy:", pipeline.score(X, y))

Pipeline Accuracy: 0.9733333333333334


## Visualizing Pipelines

Understanding pipeline structure is important for debugging and documentation purposes.

A pipeline can be inspected by printing its structure.

In [10]:
print(pipeline)

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('classifier', LogisticRegression(max_iter=1000))])


The printed output shows the sequence of operations executed within the pipeline. Each preprocessing step is applied before the final machine learning model.

## Feature Engineering

Feature engineering is the process of creating new features or modifying existing features to improve model performance.

Good features often contribute more to model performance than complex algorithms.

Common feature engineering techniques include:

- Polynomial features
- Feature interactions
- Date feature extraction
- Aggregation features
- Domain-specific transformations

In [11]:
from sklearn.preprocessing import PolynomialFeatures

X_small = [[2, 3],
           [4, 5],
           [6, 7]]

poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X_small)

print(X_poly)

[[ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]
 [ 1.  6.  7. 36. 42. 49.]]


PolynomialFeatures generates additional features based on mathematical combinations of existing features. These new features can help linear models capture non-linear relationships.

In [12]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

exercise_data = pd.DataFrame({
    "Age": [20, 25, np.nan, 30, 35],
    "Income": [3000, np.nan, 4500, 5000, 5500]
})

imputer = SimpleImputer(strategy="mean")

result = imputer.fit_transform(exercise_data)

print(result)

[[  20.  3000. ]
 [  25.  4500. ]
 [  27.5 4500. ]
 [  30.  5000. ]
 [  35.  5500. ]]


In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_result = scaler.fit_transform(result)

print(scaled_result)

[[-1.5        -1.79284291]
 [-0.5         0.        ]
 [ 0.          0.        ]
 [ 0.5         0.5976143 ]
 [ 1.5         1.19522861]]


In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    iris.data,
    iris.target,
    test_size=0.2,
    random_state=42
)

pipeline.fit(X_train, y_train)

accuracy = pipeline.score(X_test, y_test)

print("Test Accuracy:", accuracy)

Test Accuracy: 1.0


# Discussion

This chapter demonstrated the importance of preprocessing before training machine learning models.

Several preprocessing techniques were explored, including handling missing values, scaling numerical features, encoding categorical variables, constructing pipelines, and performing feature engineering.

The experiments showed that preprocessing helps create cleaner datasets and improves model readiness for machine learning algorithms. Pipelines further simplify workflow management by combining multiple preprocessing and modeling steps into a single reusable structure.

# Conclusion

Data preprocessing is a critical stage in the machine learning workflow. Raw datasets often contain missing values, inconsistent formats, and categorical features that require transformation before model training.

This chapter introduced essential preprocessing techniques such as imputation, scaling, encoding, pipelines, and feature engineering. These methods help improve data quality and create more reliable machine learning models.

Understanding these preprocessing techniques provides a strong foundation for the dimensionality reduction methods that will be explored in the next chapter.