# Chapter 5: Matrices (Part 1)

## Summary

Matrices are one of the most important structures in linear algebra. They provide an efficient way to organize, store, and manipulate large amounts of numerical information.

Matrices are heavily used in machine learning, computer vision, deep learning, scientific computing, and data analysis.

This chapter introduces matrix notation, dimensions, matrix creation, matrix indexing, transposition, and basic matrix operations.

## Learning Objectives

After completing this chapter, students should be able to:

- Define matrices.
- Understand matrix dimensions.
- Create matrices using NumPy.
- Access matrix elements.
- Compute matrix transposes.
- Perform matrix addition and subtraction.

## Theory: What is a Matrix?

A matrix is a rectangular arrangement of numbers organized into rows and columns.

Example:

[[1,2,3],
 [4,5,6]]

Matrices are used to represent datasets, images, transformations, and machine learning features.

They are fundamental building blocks in modern data science.

In [1]:
import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6]
])

print(A)

[[1 2 3]
 [4 5 6]]


## Code Explanation

The matrix contains two rows and three columns.

Each entry is identified by its row and column position.

Matrices provide a structured representation of numerical information.

## Theory: Matrix Dimensions

The size of a matrix is described by:

Rows × Columns

Examples:

2 × 3

3 × 3

4 × 2

Matrix dimensions determine which operations are mathematically valid.

In [2]:
print(A.shape)

(2, 3)


## Code Explanation

The shape function returns the dimensions of a matrix.

The output:

(2,3)

means:

- 2 rows
- 3 columns

## Theory: Matrix Elements

Every matrix entry has a specific location.

Notation:

A(i,j)

where:

- i = row
- j = column

Accessing individual elements is important for data manipulation and numerical computation.

In [3]:
print(A[0,0])
print(A[1,2])

1
6


## Theory: Matrix Transpose

The transpose of a matrix swaps rows and columns.

Example:

Original:

[[1,2,3],
 [4,5,6]]

Transpose:

[[1,4],
 [2,5],
 [3,6]]

Transpose operations are widely used in machine learning and matrix multiplication.

In [4]:
AT = A.T

print(AT)

[[1 4]
 [2 5]
 [3 6]]


## Code Explanation

The transpose operation changes matrix orientation.

Rows become columns and columns become rows.

This operation appears frequently in regression, optimization, and neural networks.

## Theory: Matrix Addition

Matrices can be added only when they have identical dimensions.

Addition is performed element by element.

Example:

[[1,2],
 [3,4]]

+

[[5,6],
 [7,8]]

In [5]:
B = np.array([
    [1,1,1],
    [1,1,1]
])

C = A + B

print(C)

[[2 3 4]
 [5 6 7]]


## Theory: Matrix Subtraction

Matrix subtraction follows the same rules as matrix addition.

Corresponding elements are subtracted from each other.

Matrices must have matching dimensions.

In [6]:
D = A - B

print(D)

[[0 1 2]
 [3 4 5]]


## Key Takeaways

- Matrices organize numerical information.
- Matrix dimensions describe size.
- Matrix elements can be accessed individually.
- Transpose swaps rows and columns.
- Matrix addition and subtraction require matching dimensions.

## Discussion

Matrices extend vector concepts by organizing data into rows and columns.

They are widely used to represent datasets and perform numerical computations.

Understanding matrix structure and dimensions is essential before learning matrix multiplication and advanced decompositions.

## Conclusion

This chapter introduced matrices, matrix dimensions, matrix elements, transposition, addition, and subtraction.

Matrices provide a powerful framework for representing and manipulating data.

These concepts form the foundation for more advanced matrix operations that appear throughout machine learning and data science.