# Chapter 9: Orthogonal Matrices and QR Decomposition

## Summary

Orthogonality is one of the most important concepts in linear algebra. Orthogonal vectors and matrices simplify many computations and provide the foundation for advanced techniques such as QR decomposition, Principal Component Analysis (PCA), and numerical optimization.

This chapter introduces orthogonal matrices, orthonormal vectors, and QR decomposition.

## Learning Objectives

After completing this chapter, students should be able to:

- Understand orthogonal vectors.
- Understand orthogonal matrices.
- Verify orthogonality.
- Explain orthonormal bases.
- Perform QR decomposition.
- Understand QR applications in data science.

## Theory: Orthogonal Vectors

Two vectors are orthogonal when their dot product equals zero.

Example:

v₁ · v₂ = 0

Orthogonality indicates that vectors are perpendicular to each other.

Orthogonal vectors play an important role in geometry, statistics, and machine learning.

In [1]:
import numpy as np

v1 = np.array([1, 0])

v2 = np.array([0, 1])

print(np.dot(v1, v2))

0


## Code Explanation

The dot product equals zero.

This confirms that the vectors are orthogonal.

Orthogonal vectors are independent and share no directional overlap.

## Theory: Orthonormal Vectors

Orthonormal vectors satisfy two conditions:

1. Orthogonal to each other.
2. Magnitude equals one.

Orthonormal bases simplify many matrix operations and decompositions.

In [2]:
u1 = np.array([1, 0])

u2 = np.array([0, 1])

print(np.linalg.norm(u1))
print(np.linalg.norm(u2))

1.0
1.0


## Code Explanation

Both vectors have magnitude equal to one.

Since they are also orthogonal, they form an orthonormal basis.

## Theory: Orthogonal Matrices

A matrix is orthogonal if:

QᵀQ = I

where:

- Qᵀ is the transpose.
- I is the identity matrix.

Orthogonal matrices preserve distances and angles.

In [3]:
Q = np.array([
    [0, -1],
    [1,  0]
])

print(Q.T @ Q)

[[1 0]
 [0 1]]


## Theory: Properties of Orthogonal Matrices

Important properties:

- Q⁻¹ = Qᵀ
- Preserve vector lengths.
- Preserve angles.
- Numerically stable.

These properties make orthogonal matrices valuable in scientific computing.

In [4]:
Q_inv = np.linalg.inv(Q)

print(Q_inv)
print("\nTranspose:")
print(Q.T)

[[ 0.  1.]
 [-1. -0.]]

Transpose:
[[ 0  1]
 [-1  0]]


## Theory: QR Decomposition

QR decomposition factors a matrix into:

A = QR

Where:

- Q = Orthogonal Matrix
- R = Upper Triangular Matrix

QR decomposition is widely used in numerical linear algebra and least squares problems.

In [5]:
A = np.array([
    [1, 2],
    [3, 4]
])

Q, R = np.linalg.qr(A)

print("Q Matrix:")
print(Q)

print("\nR Matrix:")
print(R)

Q Matrix:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]

R Matrix:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


## Code Explanation

The QR decomposition separates a matrix into an orthogonal component and an upper triangular component.

This decomposition simplifies many numerical computations.

In [6]:
reconstructed = Q @ R

print(reconstructed)

[[1. 2.]
 [3. 4.]]


## Applications in Data Science

QR decomposition is used in:

- Least Squares Regression
- Numerical Optimization
- Principal Component Analysis
- Signal Processing

It provides stable and efficient matrix computations.

## Machine Learning Connection

Many machine learning algorithms rely on orthogonal transformations to improve numerical stability and computational efficiency.

QR decomposition is commonly used in regression and dimensionality reduction techniques.

## Discussion

Orthogonality simplifies mathematical computations and improves numerical stability.

QR decomposition provides a practical method for analyzing matrices and solving optimization problems.

These concepts form a foundation for advanced topics such as eigendecomposition and singular value decomposition.

## Conclusion

This chapter introduced orthogonal vectors, orthogonal matrices, orthonormal bases, and QR decomposition.

These concepts are fundamental in numerical linear algebra and machine learning.

A strong understanding of orthogonality helps prepare students for eigendecomposition, least squares estimation, and dimensionality reduction methods.