# Chapter 10: Row Reduction and LU Decomposition

## Summary

This chapter introduces systems of linear equations and demonstrates how matrix operations can be used to solve them.

Topics include row reduction, Gaussian elimination, Gauss-Jordan elimination, matrix inversion using elimination methods, LU decomposition, and permutation matrices.

These techniques are fundamental in numerical linear algebra and form the basis of many machine learning algorithms.

## Learning Objectives

After completing this chapter, students should be able to:

- Represent systems of equations as matrices.
- Perform row reduction.
- Apply Gaussian elimination.
- Apply Gauss-Jordan elimination.
- Compute matrix inverses using elimination.
- Understand LU decomposition.
- Use permutation matrices for row swaps.

## Theory: Systems of Equations

A system of linear equations consists of multiple equations containing shared variables.

Example:

2x + y = 5

x - y = 1

The goal is to find values of x and y that satisfy all equations simultaneously.

Linear systems appear frequently in engineering, statistics, machine learning, and optimization problems.

In [21]:
import numpy as np

A = np.array([
    [2, 1],
    [1, -1]
])

b = np.array([
    [5],
    [1]
])

print("Coefficient Matrix:")
print(A)

print("\nTarget Vector:")
print(b)


Coefficient Matrix:
[[ 2  1]
 [ 1 -1]]

Target Vector:
[[5]
 [1]]


## Code Explanation

The matrix A contains the coefficients of the variables.

The vector b contains the constants on the right side of the equations.

This representation converts a system of equations into matrix form.

## Theory: Converting Equations into Matrix Form

Any linear system can be written as:

Ax = b

where:

- A is the coefficient matrix.
- x is the unknown variable vector.
- b is the result vector.

This compact representation simplifies calculations and allows efficient computer implementation.

In [22]:
x = np.linalg.solve(A, b)

print("Solution:")
print(x)

Solution:
[[2.]
 [1.]]


## Code Explanation

The NumPy function solve() computes the values of the unknown variables.

The solution satisfies all equations simultaneously.

## Theory: Matrix Equations

A matrix equation is an equation involving matrices and vectors.

The equation:

Ax = b

can be interpreted as finding a vector x that transforms through matrix A into vector b.

Many machine learning models are based on solving matrix equations.

In [23]:
verification = A @ x

print("Verification:")
print(verification)

Verification:
[[5.]
 [1.]]


## Theory: Row Reduction

Row reduction transforms a matrix into a simpler form using elementary row operations.

Allowed operations:

1. Swap rows.
2. Multiply a row by a nonzero scalar.
3. Add multiples of one row to another row.

These operations preserve the solution of the system.

In [24]:
M = np.array([
    [2., 1., 5.],
    [1., -1., 1.]
])

print(M)

[[ 2.  1.  5.]
 [ 1. -1.  1.]]


## Augmented Matrix

An augmented matrix combines the coefficient matrix and result vector into one matrix.

This format is commonly used during elimination procedures.

In [25]:
M[0] = M[0] / 2

print(M)

[[ 1.   0.5  2.5]
 [ 1.  -1.   1. ]]


## Code Explanation

The first row is divided by 2.

This operation creates a leading 1, making subsequent elimination steps easier.

In [26]:
M[1] = M[1] - M[0]

print(M)

[[ 1.   0.5  2.5]
 [ 0.  -1.5 -1.5]]


## Theory: Gaussian Elimination

Gaussian elimination transforms a matrix into upper triangular form.

The objective is to eliminate entries below the pivot positions.

After elimination, back substitution can be used to obtain the solution.

In [27]:
A2 = np.array([
    [2., 1.],
    [1., -1.]
])

b2 = np.array([
    [5.],
    [1.]
])

solution = np.linalg.solve(A2, b2)

print(solution)

[[2.]
 [1.]]


## Discussion

Systems of equations can be efficiently represented using matrices.

Row operations provide a systematic way to simplify matrices while preserving solutions.

Gaussian elimination is one of the most important algorithms in numerical linear algebra.

## Theory: Gaussian Elimination Procedure

Gaussian Elimination transforms a matrix into Row Echelon Form (REF).

Characteristics of REF:

- Leading entries move to the right as rows progress downward.
- Entries below pivots are zero.
- Rows consisting entirely of zeros appear at the bottom.

Once REF is obtained, back-substitution can be used to solve the system.

In [28]:
M = np.array([
    [1., 0.5, 2.5],
    [0., -1.5, -1.5]
])

print(M)

[[ 1.   0.5  2.5]
 [ 0.  -1.5 -1.5]]


## Code Explanation

The matrix has already undergone one elimination step.

The lower-left element is zero, which satisfies one of the requirements for row echelon form.

In [29]:
x2 = (-1.5) / (-1.5)

print("x2 =", x2)

x2 = 1.0


In [30]:
x1 = 2.5 - (0.5 * x2)

print("x1 =", x1)

x1 = 2.0


## Theory: Back Substitution

After Gaussian elimination, variables are solved starting from the last equation and moving upward.

This process is called back substitution.

Back substitution is computationally efficient and widely used in numerical methods.

## Theory: Gauss-Jordan Elimination

Gauss-Jordan Elimination extends Gaussian Elimination.

Instead of eliminating only entries below pivots, it eliminates entries both above and below pivots.

The goal is to obtain Reduced Row Echelon Form (RREF).

In [31]:
R = np.array([
    [1., 0.5, 2.5],
    [0., 1., 1.]
])

R[0] = R[0] - (0.5 * R[1])

print(R)

[[1. 0. 2.]
 [0. 1. 1.]]


## Code Explanation

The value above the pivot is eliminated.

This operation moves the matrix closer to Reduced Row Echelon Form.

In [32]:
RREF = np.array([
    [1., 0., 2.],
    [0., 1., 1.]
])

print(RREF)

[[1. 0. 2.]
 [0. 1. 1.]]


## Theory: Reduced Row Echelon Form

A matrix is in RREF when:

- Every pivot equals 1.
- Each pivot is the only nonzero value in its column.
- Pivot positions move rightward as rows progress downward.

RREF directly reveals the solution to the system.

## Theory: Matrix Inverse via Gauss-Jordan Elimination

One method for computing matrix inverses involves augmenting a matrix with the identity matrix.

Example:

[A | I]

Row operations are then applied until:

[I | A⁻¹]

is obtained.

In [33]:
A = np.array([
    [1., 2.],
    [3., 4.]
])

A_inv = np.linalg.inv(A)

print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


## Code Explanation

Although NumPy computes the inverse directly, internally many algorithms rely on elimination-based procedures.

The inverse matrix reverses the effect of the original matrix.

## Theory: LU Decomposition

LU Decomposition factors a matrix into:

A = LU

where:

- L = Lower Triangular Matrix
- U = Upper Triangular Matrix

LU decomposition simplifies solving systems of equations.

In [34]:
from scipy.linalg import lu

A = np.array([
    [2., 1.],
    [4., 3.]
])

P, L, U = lu(A)

print("L Matrix:")
print(L)

print("\nU Matrix:")
print(U)

L Matrix:
[[1.  0. ]
 [0.5 1. ]]

U Matrix:
[[ 4.   3. ]
 [ 0.  -0.5]]


## Code Explanation

The matrix is decomposed into lower and upper triangular components.

This factorization reduces computational complexity when solving multiple systems involving the same matrix.

## Theory: Permutation Matrices

Row swaps can be represented using permutation matrices.

Permutation matrices contain:

- Exactly one value of 1 in each row.
- Exactly one value of 1 in each column.

They preserve matrix structure while changing row order.

In [35]:
P = np.array([
    [0,1],
    [1,0]
])

A = np.array([
    [1,2],
    [3,4]
])

print(P @ A)

[[3 4]
 [1 2]]


## Discussion

Gaussian Elimination, Gauss-Jordan Elimination, matrix inversion, LU decomposition, and permutation matrices provide efficient methods for solving systems of equations.

These techniques are fundamental in numerical linear algebra and appear frequently in machine learning, optimization, and scientific computing.

## Theory: Verifying LU Decomposition

After decomposing a matrix into L and U matrices, it is important to verify the decomposition.

The verification step checks whether:

A = LU

If the multiplication of L and U reconstructs the original matrix, the decomposition is correct.

In [36]:
A_reconstructed = L @ U

print(A_reconstructed)

[[4. 3.]
 [2. 1.]]


## Code Explanation

The product of L and U should match the original matrix.

Small numerical differences may occur due to floating-point precision.

## Theory: Solving Systems Using LU Decomposition

LU decomposition allows a system of equations to be solved in two stages.

Given:

Ax = b

and

A = LU

The solution process becomes:

Ly = b

followed by:

Ux = y

This approach is often faster than repeatedly performing Gaussian elimination.

In [37]:
b = np.array([
    [5.],
    [11.]
])

y = np.linalg.solve(L, b)

x = np.linalg.solve(U, y)

print("Solution:")
print(x)

Solution:
[[ 14.]
 [-17.]]


## Code Explanation

The problem is divided into two smaller systems.

First, the intermediate vector y is computed.

Second, the final solution vector x is obtained.

## Theory: Computational Efficiency

LU decomposition is particularly useful when multiple systems share the same coefficient matrix.

Instead of repeatedly decomposing the matrix, the decomposition can be reused.

This significantly reduces computational cost.

In [38]:
A = np.array([
    [3., 1.],
    [1., 2.]
])

P, L, U = lu(A)

print("Lower Matrix:")
print(L)

print("\nUpper Matrix:")
print(U)

Lower Matrix:
[[1.         0.        ]
 [0.33333333 1.        ]]

Upper Matrix:
[[3.         1.        ]
 [0.         1.66666667]]


## Theory: Numerical Stability

Numerical stability refers to how algorithms behave when small computational errors occur.

Some matrix operations amplify rounding errors.

LU decomposition with pivoting improves numerical stability.

In [39]:
print("Permutation Matrix:")
print(P)

Permutation Matrix:
[[1. 0.]
 [0. 1.]]


## Code Explanation

The permutation matrix records row exchanges performed during decomposition.

These exchanges help avoid unstable calculations.

## Theory: Pivoting

Pivoting rearranges rows to place larger values in pivot positions.

Benefits include:

- Improved numerical stability.
- Reduced rounding errors.
- More reliable solutions.

Most professional numerical software performs pivoting automatically.

In [40]:
A = np.array([
    [0., 2.],
    [1., 3.]
])

P, L, U = lu(A)

print("P Matrix:")
print(P)

print("\nL Matrix:")
print(L)

print("\nU Matrix:")
print(U)

P Matrix:
[[0. 1.]
 [1. 0.]]

L Matrix:
[[1. 0.]
 [0. 1.]]

U Matrix:
[[1. 3.]
 [0. 2.]]


## Theory: Applications of LU Decomposition

LU decomposition is widely used in:

- Linear Regression
- Optimization
- Engineering Simulations
- Scientific Computing
- Numerical Analysis

Many machine learning algorithms indirectly rely on matrix factorization methods.

## Machine Learning Connection

Large-scale machine learning systems frequently solve systems of linear equations.

Matrix factorizations such as LU decomposition make these computations more efficient and scalable.

## Key Takeaways

- LU decomposition factors matrices into lower and upper triangular matrices.
- LU decomposition simplifies solving systems of equations.
- Permutation matrices track row swaps.
- Pivoting improves numerical stability.
- LU decomposition is widely used in machine learning and scientific computing.

## Chapter Discussion

Row reduction techniques provide systematic approaches for solving systems of equations.

Gaussian elimination and LU decomposition are among the most important algorithms in numerical linear algebra because they enable efficient and reliable computations.

## Summary

This chapter introduced:

- Systems of Equations
- Matrix Representation
- Row Reduction
- Gaussian Elimination
- Gauss-Jordan Elimination
- Matrix Inverses
- LU Decomposition
- Permutation Matrices

Together, these concepts form a core toolkit for numerical problem solving.

## Reflection

Understanding row reduction and matrix factorization improves insight into how computers solve large systems of equations.

These techniques are foundational for advanced machine learning and optimization algorithms.

## Conclusion

Row reduction and LU decomposition provide efficient methods for solving systems of equations and analyzing matrices.

These techniques improve computational efficiency and numerical stability, making them essential tools in modern data science and machine learning workflows.