# Chapter 13: Eigendecomposition

## Summary

Eigendecomposition is one of the most important matrix decomposition techniques in linear algebra.

It reveals fundamental properties of matrices by expressing them in terms of eigenvalues and eigenvectors.

Eigendecomposition has applications in machine learning, data compression, signal processing, computer vision, and Principal Component Analysis (PCA).

## Learning Objectives

After completing this chapter, students should be able to:

- Define eigenvalues and eigenvectors.
- Understand the eigendecomposition process.
- Compute eigenvalues and eigenvectors using Python.
- Verify eigendecomposition results.
- Interpret eigenvectors geometrically.
- Understand applications in machine learning.

## Theory: Eigenvectors

An eigenvector is a special vector whose direction remains unchanged after a matrix transformation.

For a matrix A and vector v:

Av = λv

where:

- v is an eigenvector
- λ is an eigenvalue

The transformation changes only the magnitude of the vector.

In [1]:
import numpy as np

A = np.array([
    [3, 1],
    [0, 2]
])

print(A)

[[3 1]
 [0 2]]


## Code Explanation

The matrix A will be used throughout this chapter to demonstrate eigenvalues and eigenvectors.

The goal is to identify vectors that maintain their direction after transformation by A.

## Theory: Eigenvalues

Eigenvalues describe how much an eigenvector is stretched or compressed during transformation.

If:

Av = λv

then λ indicates the scaling factor.

Large eigenvalues correspond to directions with greater variance or influence.

In [2]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

Eigenvalues:
[3. 2.]


## Code Explanation

The eig() function computes the eigenvalues and eigenvectors of a square matrix.

The resulting eigenvalues describe the scaling behavior of the matrix.

In [3]:
print("Eigenvectors:")
print(eigenvectors)

Eigenvectors:
[[ 1.         -0.70710678]
 [ 0.          0.70710678]]


## Theory: Interpreting Eigenvectors

Each column of the eigenvector matrix corresponds to an eigenvalue.

Eigenvectors identify special directions that remain unchanged under the matrix transformation.

These directions often reveal important patterns within data.

In [4]:
v = eigenvectors[:,0]

print(v)

[1. 0.]


In [5]:
lambda_1 = eigenvalues[0]

Av = A @ v

lambda_v = lambda_1 * v

print("Av:")
print(Av)

print("\nλv:")
print(lambda_v)

Av:
[3. 0.]

λv:
[3. 0.]


## Code Explanation

The equality:

Av = λv

can be verified numerically.

If both results match, the vector is an eigenvector associated with the selected eigenvalue.

## Theory: Why Eigendecomposition Matters

Many machine learning algorithms rely on eigendecomposition.

Examples include:

- Principal Component Analysis (PCA)
- Spectral Clustering
- Dimensionality Reduction
- Signal Analysis

Eigenvectors reveal important directions within data.

In [6]:
D = np.diag(eigenvalues)

print(D)

[[3. 0.]
 [0. 2.]]


## Theory: Diagonal Matrix of Eigenvalues

The eigenvalues are often stored in a diagonal matrix.

This matrix forms part of the eigendecomposition equation:

A = VDV⁻¹

where:

- V contains eigenvectors
- D contains eigenvalues

In [7]:
V = eigenvectors

print(V)

[[ 1.         -0.70710678]
 [ 0.          0.70710678]]


## Applications in Data Science

Eigenvalues and eigenvectors are used in:

- PCA
- Feature Extraction
- Face Recognition
- Image Compression
- Recommendation Systems

They help identify important patterns and reduce data complexity.

## Discussion

Eigendecomposition provides insight into how matrices transform vectors.

By analyzing eigenvalues and eigenvectors, important structural information can be extracted from data and mathematical systems.

## Conclusion

This section introduced eigenvalues, eigenvectors, and their interpretation.

These concepts form the foundation of eigendecomposition and are essential for understanding dimensionality reduction and many machine learning algorithms.

## Theory: Eigendecomposition Formula

A matrix can be decomposed into three matrices:

A = VDV⁻¹

where:

- A is the original matrix
- V contains eigenvectors
- D contains eigenvalues
- V⁻¹ is the inverse of V

This factorization reveals the internal structure of a matrix and simplifies many computations.

In [8]:
V = eigenvectors

D = np.diag(eigenvalues)

V_inv = np.linalg.inv(V)

print("V:")
print(V)

print("\nD:")
print(D)

print("\nV^-1:")
print(V_inv)

V:
[[ 1.         -0.70710678]
 [ 0.          0.70710678]]

D:
[[3. 0.]
 [0. 2.]]

V^-1:
[[1.         1.        ]
 [0.         1.41421356]]


## Code Explanation

The eigendecomposition separates the matrix into eigenvectors and eigenvalues.

This representation often makes mathematical analysis easier than working with the original matrix directly.

In [10]:
A_reconstructed = V @ D @ V_inv

print(A_reconstructed)

[[3. 1.]
 [0. 2.]]


## Theory: Matrix Reconstruction

If the eigendecomposition is correct, multiplying:

VDV⁻¹

should reconstruct the original matrix.

This provides a useful verification of the decomposition.

In [11]:
print("Original Matrix:")
print(A)

print("\nReconstructed Matrix:")
print(A_reconstructed)

Original Matrix:
[[3 1]
 [0 2]]

Reconstructed Matrix:
[[3. 1.]
 [0. 2.]]


## Theory: Symmetric Matrices

Symmetric matrices satisfy:

A = Aᵀ

Symmetric matrices have several useful properties:

- Real eigenvalues
- Orthogonal eigenvectors
- Improved numerical stability

Many machine learning applications involve symmetric matrices.

In [12]:
S = np.array([
    [2, 1],
    [1, 2]
])

eigvals_S, eigvecs_S = np.linalg.eig(S)

print("Eigenvalues:")
print(eigvals_S)

print("\nEigenvectors:")
print(eigvecs_S)

Eigenvalues:
[3. 1.]

Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## Code Explanation

The symmetric matrix produces real eigenvalues and orthogonal eigenvectors.

These properties make symmetric matrices particularly important in machine learning and statistics.

## Theory: Dominant Eigenvalue

The dominant eigenvalue is the eigenvalue with the largest magnitude.

Its corresponding eigenvector often captures the most important direction of variation in the data.

This idea is central to Principal Component Analysis (PCA).

In [13]:
dominant_index = np.argmax(
    np.abs(eigenvalues)
)

dominant_eigenvalue = eigenvalues[
    dominant_index
]

print(dominant_eigenvalue)

3.0


## Theory: Eigenvectors and Data Variance

In many datasets, directions associated with larger eigenvalues contain more information.

Dimensionality reduction techniques preserve these important directions while discarding less informative ones.

In [14]:
dominant_eigenvector = eigenvectors[
    :,
    dominant_index
]

print(dominant_eigenvector)

[1. 0.]


## Theory: Principal Component Analysis

PCA uses eigenvalues and eigenvectors of a covariance matrix.

The principal components correspond to eigenvectors associated with the largest eigenvalues.

PCA is widely used for:

- Feature reduction
- Data visualization
- Noise reduction

In [15]:
cov_matrix = np.array([
    [3, 1],
    [1, 2]
])

eigvals_cov, eigvecs_cov = np.linalg.eig(
    cov_matrix
)

print(eigvals_cov)

[3.61803399 1.38196601]


## Code Explanation

The eigenvalues indicate how much variance exists along each principal direction.

Larger eigenvalues correspond to more informative directions.

## Applications in Machine Learning

Eigendecomposition is widely used in:

- Principal Component Analysis (PCA)
- Spectral Clustering
- Recommendation Systems
- Computer Vision
- Signal Processing

These methods rely on extracting meaningful structure from matrices.

## Key Takeaways

- Eigendecomposition factors a matrix into VDV⁻¹.
- Eigenvalues describe scaling effects.
- Eigenvectors describe important directions.
- Symmetric matrices have useful mathematical properties.
- PCA relies heavily on eigendecomposition.

## Discussion

Eigendecomposition provides a powerful framework for understanding matrix transformations.

By examining eigenvalues and eigenvectors, hidden structure and important directions within data can be identified and analyzed.

## Conclusion

This chapter explored eigendecomposition, matrix reconstruction, symmetric matrices, dominant eigenvalues, and applications in PCA.

These concepts are fundamental to modern machine learning, data analysis, and dimensionality reduction techniques.