# Chapter 14: Singular Value Decomposition (SVD)

## Summary

Singular Value Decomposition (SVD) is one of the most powerful matrix decomposition techniques in linear algebra.

SVD factorizes a matrix into three simpler matrices and provides insights into the structure, rank, and information content of data.

SVD is widely used in machine learning, recommendation systems, image compression, natural language processing, and dimensionality reduction.

## Learning Objectives

After completing this chapter, students should be able to:

- Understand the concept of Singular Value Decomposition.
- Interpret the matrices U, Σ, and Vᵀ.
- Compute SVD using Python.
- Reconstruct matrices from SVD components.
- Understand the relationship between SVD and PCA.
- Explain practical applications of SVD.

## Theory: What is Singular Value Decomposition?

Singular Value Decomposition factorizes a matrix A into:

A = UΣVᵀ

where:

- U contains left singular vectors.
- Σ contains singular values.
- Vᵀ contains right singular vectors.

Unlike eigendecomposition, SVD can be applied to any matrix, including non-square matrices.

In [1]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(A)

[[1 2]
 [3 4]
 [5 6]]


## Code Explanation

The matrix A is a rectangular matrix with three rows and two columns.

Unlike eigendecomposition, SVD can be performed on rectangular matrices.

## Theory: Components of SVD

The decomposition produces three matrices:

U → Left singular vectors

Σ → Singular values

Vᵀ → Right singular vectors

Together these matrices completely describe the original matrix.

In [2]:
U, s, VT = np.linalg.svd(A)

print("U Matrix:")
print(U)

U Matrix:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


In [3]:
print("Singular Values:")
print(s)

Singular Values:
[9.52551809 0.51430058]


In [4]:
print("VT Matrix:")
print(VT)

VT Matrix:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


## Code Explanation

The svd() function computes the singular value decomposition of a matrix.

The output includes singular vectors and singular values that describe the structure of the matrix.

## Theory: Singular Values

Singular values indicate the importance of each component of the matrix.

Large singular values correspond to directions containing more information.

Small singular values often correspond to noise or less important information.

In [5]:
Sigma = np.zeros(
    (
        A.shape[0],
        A.shape[1]
    )
)

np.fill_diagonal(
    Sigma,
    s
)

print(Sigma)

[[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


## Theory: Sigma Matrix

The Sigma matrix contains singular values arranged along its diagonal.

All off-diagonal entries are zero.

The singular values are typically ordered from largest to smallest.

In [6]:
print("Rank:")
print(np.linalg.matrix_rank(A))

Rank:
2


## Theory: Matrix Rank

The rank of a matrix indicates the number of independent directions contained within the data.

SVD provides a natural way to understand matrix rank through singular values.

In [7]:
nonzero_sv = np.sum(
    s > 1e-10
)

print(nonzero_sv)

2


## Code Explanation

The number of nonzero singular values equals the rank of the matrix.

This property makes SVD useful for analyzing data structure and dimensionality.

## Applications in Data Science

SVD is widely used in:

- Recommendation Systems
- Image Compression
- Natural Language Processing
- Data Compression
- Dimensionality Reduction

Many modern machine learning systems rely on SVD-based techniques.

## Discussion

SVD provides a robust and flexible method for understanding matrix structure.

Because it can be applied to any matrix, it is one of the most important tools in numerical linear algebra.

## Conclusion

This section introduced Singular Value Decomposition, singular values, matrix rank, and the components of SVD.

These concepts provide the foundation for matrix reconstruction, dimensionality reduction, and many machine learning applications.

## Theory: Matrix Reconstruction

One of the most important properties of SVD is that the original matrix can be reconstructed from its decomposition.

The reconstruction formula is:

A = UΣVᵀ

If the decomposition is correct, the reconstructed matrix should closely match the original matrix.

In [8]:
explained_information = (
    s**2 /
    np.sum(s**2)
)

print(explained_information)

[0.99709335 0.00290665]


## Theory: Information Content

The squared singular values indicate how much information is captured by each component.

Components associated with larger singular values explain more variance in the data.

In [9]:
cumulative_information = np.cumsum(
    explained_information
)

print(cumulative_information)

[0.99709335 1.        ]


## Theory: Relationship Between SVD and PCA

Principal Component Analysis (PCA) is closely related to SVD.

PCA identifies directions of maximum variance in data.

In practice, many PCA implementations use SVD because it is numerically stable and computationally efficient.

In [10]:
X = np.array([
    [2,1],
    [3,2],
    [4,3],
    [5,4]
])

X_centered = X - np.mean(
    X,
    axis=0
)

U_pca, s_pca, VT_pca = np.linalg.svd(
    X_centered
)

print(VT_pca)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


## Code Explanation

The right singular vectors identify the principal directions within the dataset.

These directions correspond to principal components in PCA.

## Theory: Image Compression

Image compression is one of the most famous applications of SVD.

Instead of storing every pixel value, a compressed representation can be created using only the largest singular values.

This significantly reduces storage requirements.

## Applications in Machine Learning

SVD is widely used in:

- Principal Component Analysis (PCA)
- Recommendation Systems
- Latent Semantic Analysis (LSA)
- Image Compression
- Feature Extraction
- Noise Reduction

These applications make SVD one of the most valuable matrix decomposition techniques.

## Key Takeaways

- SVD decomposes a matrix into U, Σ, and Vᵀ.
- Matrices can be reconstructed from SVD components.
- Low-rank approximation reduces complexity.
- SVD enables dimensionality reduction.
- PCA is closely related to SVD.

## Discussion

Singular Value Decomposition provides a powerful framework for analyzing matrix structure and extracting meaningful information from data.

Its ability to perform dimensionality reduction and matrix approximation makes it an essential technique in machine learning and data science.

## Conclusion

This chapter introduced Singular Value Decomposition, matrix reconstruction, low-rank approximation, dimensionality reduction, and the relationship between SVD and PCA.

SVD is one of the most important techniques in modern machine learning because it enables efficient data representation, feature extraction, and information compression.